### ISSUE TITLE
Todays build

### ISSUE THREAD

**Issue by Adminisnyator** [WayfireWM/wcm#27] opened 2020-12-29 13:40 UTC

**Comment by ammen99** [comment] 2020-12-29 13:42
what is the exact issue here?

**Comment by Adminisnyator** [comment] 2020-12-29 13:56
Oh sorry. Did not mean to send it yet. Somehow misclicked. Anywho, the current git version of wf-config paired together with wayfire (both from master each) cause:
 terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

**Comment by Adminisnyator** [comment] 2020-12-29 13:56
I

**Comment by ammen99** [comment] 2020-12-30 07:44
> Oh sorry. Did not mean to send it yet. Somehow misclicked. Anywho, the current git version of wf-config paired together with wayfire (both from master each) cause:
> terminate called after throwing an instance of 'std::logic_error'
> what(): basic_string::_M_construct null not valid

Is this crash happening in WCM or in Wayfire?

**Comment by damianatorrpm** [comment] 2020-12-30 08:28
in wayfire, same thing here

**Comment by damianatorrpm** [comment] 2020-12-30 08:29
i mean wcm

**Comment by Adminisnyator** [comment] 2020-12-30 13:59
Not a priority one though. Bye the way, in what way should I report such finds in the future? Ill be staying at the newest build for a bit and do not want to spam the issues area.

**Comment by ammen99** [comment] 2020-12-30 14:18
I think opening issues is fine :)

**Comment by soreau** [comment] 2020-12-30 14:42
I believe this bug was recently fixed in wcm. Does it happen with latest wcm from git?

**Comment by Adminisnyator** [comment] 2020-12-30 15:16
Still happening with a rebuild a few minutes ago. Rebuilt wayfire, wcm, wf-config, wayfire-plugins-extra all from latest master each.

**Comment by soreau** [comment] 2020-12-30 16:00
What is happening exactly? wcm is crashing?

**Comment by Adminisnyator** [comment] 2020-12-30 16:31
Wcm crashes on start. Gives the above error message.

**Comment by soreau** [comment] 2020-12-30 16:35
I am pretty sure this has already been fixed in wcm git master.

**Comment by Adminisnyator** [comment] 2020-12-30 16:46
Did  a rebuild, it persists. 
[wcm.log](https://github.com/WayfireWM/wcm/files/5754957/wcm.log)
Any other logs that might help?

**Comment by soreau** [comment] 2020-12-30 16:49
Is there any way you can post a backtrace from gdb?

**Comment by Adminisnyator** [comment] 2020-12-30 17:18
Copy of bt for future ref
[gdb.log](https://github.com/WayfireWM/wcm/files/5755047/gdb.log)

**Comment by soreau** [comment] 2020-12-30 17:44
Ah, this is a new breakage caused by latest wf-config changes. I'm not sure how to fix it.

**Comment by soreau** [comment] 2020-12-30 22:34
I have pushed a fix, pleae reopen if it still crashes for you. Thanks for the report.

**Closed by soreau** 2020-12-30 22:34 UTC
